// <auto-generated />
namespace BazarCloth.DataBase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_OrderItem_Table_And_AddList_OrderItelINto_OrderTAble : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_OrderItem_Table_And_AddList_OrderItelINto_OrderTAble));
        
        string IMigrationMetadata.Id
        {
            get { return "201901011746353_Add_OrderItem_Table_And_AddList_OrderItelINto_OrderTAble"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
